### ISSUE TITLE
Frozen dataclass behavior change 1.6.1 -> 1.7

### ISSUE THREAD

**Issue by jdegesys** [samuelcolvin/pydantic#2065]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7
            pydantic compiled: True
                 install path: /home/user/miniconda3/envs/debug_pydantic/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, May  7 2020, 20:00:49)  [GCC 7.3.0]
                     platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.10
     optional deps. installed: []
```

This code works in v1.6.1:
```py
from dataclasses import dataclass

from pydantic import BaseModel


@dataclass(frozen=True)
class Item:
    name: str


class Example(BaseModel):
    item: Item

    class Config:
        arbitrary_types_allowed = True
```

However, in v1.7, it produces the following error:
```py
Traceback (most recent call last):
  File "/home/user/debug_pydantic.py", line 11, in <module>
    class Example(BaseModel):
  File "pydantic/main.py", line 262, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 315, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 284, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 362, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 538, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 596, in find_validators
  File "pydantic/dataclasses.py", line 222, in make_dataclass_validator
    # and only from the field() function, although Field instances are
  File "pydantic/dataclasses.py", line 214, in pydantic.dataclasses.dataclass
    type_name = self.type.__name__
  File "pydantic/dataclasses.py", line 209, in pydantic.dataclasses.dataclass.wrap
    def __init__(self, type):
  File "pydantic/dataclasses.py", line 126, in pydantic.dataclasses._process_class
    # +=======+=======+=======+========+========+
  File "/home/user/miniconda3/envs/debug_pydantic/lib/python3.8/dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File "/home/user/miniconda3/envs/debug_pydantic/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/user/miniconda3/envs/debug_pydantic/lib/python3.8/dataclasses.py", line 891, in _process_class
    raise TypeError('cannot inherit non-frozen dataclass from a '
TypeError: cannot inherit non-frozen dataclass from a frozen one
```

Looking through the changelog, this does not appear to be an intentional change. I can remove the `frozen=True` attribute of the dataclass decorator as a workaround, but this seems less than ideal.

**Comment by samuelcolvin** [comment]
I've just released v1.7.1 (it'll take 10 minutes or so to be available on pypi), please let me know if that fixes your problem.

**Comment by PrettyWood** [comment]
Hmm damn...20 min after and I would have fixed it in my PR.
v1.7.1 doesn't fix it

**Comment by PrettyWood** [comment]
@samuelcolvin I created https://github.com/samuelcolvin/pydantic/pull/2066.
I feel bad for not catching this before. Don't know if this needs a v1.7.2 but probably as we can't overwrite pypi uploads

**Comment by samuelcolvin** [comment]
no problem, these things happen. I'll release v1.7.2 tomorrow or the day after.

**Comment by yoavg** [comment]
I see a possibly related issue also in 1.8.1:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/yogo/.local/share/virtualenvs/server-Fv_PcELd/lib/python3.7/site-packages/pydantic
               python version: 3.7.9 (default, Nov 20 2020, 18:45:38)  [Clang 12.0.0 (clang-1200.0.32.27)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Here is a minimal code that fails:
```
from dataclasses import dataclass
import pydantic

from pydantic import BaseModel

@dataclass(frozen=True)
class T:
    bla: int


@dataclass(frozen=True)
class Item:
    name: str
    b: T


class Example(BaseModel):
    item: pydantic.dataclasses.dataclass(Item, frozen=True)


print(Example.schema_json())

```
