### ISSUE TITLE
[Question] Improving enum error messages

### ISSUE THREAD

**Issue by bcatubig** [samuelcolvin/pydantic#355]
# Question

Hello!

I'd like to improve the default error messages for enums to include the allowed values as defined in an enum class instead the of default `value is not a valid enumeration member` message without having to override `Configs.error_msg_templates[type_error.enum]` on the base model.

Is there a good way to parse the enum values from the Enum class?

Example:

```
class AllowedAWSInstanceTypesEnum(str, Enum):
    t2_medium = "t2.medium"
    t2_micro = "t2.micro"

class AWSBase(BaseModel):
  instance_size: AllowedAWSInstanceTypesEnum
```

#### Example Json

```json
{
    "instance_size": "m4.xlarge"
}
```

This should generate an error similar to 

```
value m4.xlarge is not valid. Must be one of ["t2.medium", "t2.micro"]
```

Thank you for your help!

**Comment by samuelcolvin** [comment]
Easy enough to iterate over an enum, but do we want to add all enum values to the default error message?

Maybe but it might lead to very long error messages, perhaps we could add "choices" to ctx then people can modify the message as they wish.

**Comment by tiangolo** [comment]
Also to have in mind: having a fixed error value, like `value is not a valid enumeration member` allows you to use it as the key of a dictionary, do `str` comparison, etc.

For example, you can check if the error value is exactly "`value is not a valid enumeration member`" to trigger a nice UI message explaining it to the final user in a more stylish way, for example translating the message to your supported languages.

If the error was "`value m4.xlarge is not valid. Must be one of ...`" you would have a hard time detecting the type of error to trigger the UI message, or to translate it, etc.

On the other side, you can get all the enum values from the JSON Schema two (I don't know if it applies to your use case), e.g.:

```Python
from enum import Enum
from pydantic import BaseModel

class AllowedAWSInstanceTypesEnum(str, Enum):
    t2_medium = "t2.medium"
    t2_micro = "t2.micro"

class AWSBase(BaseModel):
  instance_size: AllowedAWSInstanceTypesEnum

print(AWSBase.schema_json(indent=2))
```

prints:

```JSON
{
  "title": "AWSBase",
  "type": "object",
  "properties": {
    "instance_size": {
      "title": "Instance_Size",
      "enum": [
        "t2.medium",
        "t2.micro"
      ],
      "type": "string"
    }
  },
  "required": [
    "instance_size"
  ]
}
```

**Comment by samuelcolvin** [comment]
> having a fixed error value, like value is not a valid enumeration member allows you to use it as the key of a dictionary, do str comparison, etc.

This is what the `type` attribute of errors is for. I would advise against using the `msg` of errors in a lookup as they're like to change.

**Comment by tiangolo** [comment]
:facepalm: you're right.

**Comment by samuelcolvin** [comment]
Fixed I think.

**Comment by rodrigocaus** [comment]
Hello.

In Pydantic 1.6.1 the message to Enum ValidationError is in general: `value is not a valid enumeration member; permitted: ...`.
I'd like to know, in most cases, what value led to that error (not only in Enum types). The **ValidationError** ends up overlapping the **ValueError** message that usually inform such value. Is there any form of adding this in the message template or context field? 

Thank you!

**Comment by RileyMShea** [comment]
I am still experiencing this as of pydantic `1.8.1` using string enums:
```shell
>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for SubmissionResponse
E   link_flair_text
E     value is not a valid enumeration member; permitted: 'Furniture', 'Meta', 'Prebuilt', 'Controller', 'Headphones', 'PSU', 'Monitor', 'Cooler', 'RAM', 'Motherboard', 'Keyboard', 'Mouse', 'Case', 'SSD - Sata', 'SSD - M.2', 'Webcam', 'Fan', 'Other', 'Cables', 'Mic', 'Laptop', 'HDD', 'GPU', 'VR', 'Speakers', 'Missing' (type=type_error.enum; enum_values=[<BAPCSLinkFlair.Furniture: 'Furniture'>, <BAPCSLinkFlair.Meta: 'Meta'>, <BAPCSLinkFlair.Prebuilt: 'Prebuilt'>, <BAPCSLinkFlair.Controller: 'Controller'>, <BAPCSLinkFlair.Headphones: 'Headphones'>, <BAPCSLinkFlair.PSU: 'PSU'>, <BAPCSLinkFlair.Monitor: 'Monitor'>, <BAPCSLinkFlair.Cooler: 'Cooler'>, <BAPCSLinkFlair.RAM: 'RAM'>, <BAPCSLinkFlair.Motherboard: 'Motherboard'>, <BAPCSLinkFlair.Keyboard: 'Keyboard'>, <BAPCSLinkFlair.Mouse: 'Mouse'>, <BAPCSLinkFlair.Case: 'Case'>, <BAPCSLinkFlair.SSD_Sata: 'SSD - Sata'>, <BAPCSLinkFlair.SSD_M2: 'SSD - M.2'>, <BAPCSLinkFlair.Webcam: 'Webcam'>, <BAPCSLinkFlair.Fan: 'Fan'>, <BAPCSLinkFlair.Other: 'Other'>, <BAPCSLinkFlair.Cables: 'Cables'>, <BAPCSLinkFlair.Mic: 'Mic'>, <BAPCSLinkFlair.Laptop: 'Laptop'>, <BAPCSLinkFlair.HDD: 'HDD'>, <BAPCSLinkFlair.GPU: 'GPU'>, <BAPCSLinkFlair.VR: 'VR'>, <BAPCSLinkFlair.Speakers: 'Speakers'>, <BAPCSLinkFlair.Missing: 'Missing'>])
```
Not sure how to best go about debugging in situations like this.

**Comment by rodrigocaus** [comment]
It seems like the best workaround to better know what led to Enum type error is to replace the field validator:
```
class MyEnum(str, Enum):
   ...


class MyClass(BaseModel):
    field: MyEnum
    @pydantic.validator('field', pre=True)
    def validate_enum_field(cls, field: str):
        return MyEnum(field)
```
It raises a ValueError showing the value that led to Enum error, replacing the default Enum ValidationError message, and then it's wrapped by pydantic ValidationError. When Enum value is correct, the enum type of 'field' is assured.
